version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
    docker_gen: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=grafana.supergreenlab.com
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/
    networks:
      - back-tier
    restart: always

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - docker_gen:/etc/nginx/conf.d
      - ./nginx/htpasswd:/etc/nginx/htpasswd
    networks:
      - front-tier
      - back-tier
    depends_on:
      - dockergen
      - grafana
      - supergreenlab.com
    restart: always

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - docker_gen:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./nginx/htpasswd:/etc/nginx/htpasswd
    networks:
      - front-tier
      - back-tier
    depends_on:
      - grafana
      - supergreenlab.com
    restart: always

  supergreenlab.com:
    image: nginx
    environment:
      - VIRTUAL_HOST=supergreenlab.com,www.supergreenlab.com
    volumes:
      - ./supergreenlab.com/nginx:/etc/nginx/conf.d/
      - ./supergreenlab.com/html:/usr/share/nginx/html
    networks:
      - back-tier
    restart: always
